name: Deploy
on:
  push:
    branches: [prod]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key && chmod 600 key
          ssh -i key -o StrictHostKeyChecking=no root@5.161.122.7 "
            cd /opt/josh && git pull && npm install && npm run build
          "
          rm key
